### ISSUE TITLE
Issue installing SoundPipe

### ISSUE THREAD

**Issue by sashank3010** [PaulBatchelor/Soundpipe#10]
Encountered an error while installing Soundpipe. After, cloning libsndfile, sh autogen.sh did not work.

Here's the workaround (as suggested) - 
$ cd ..
$ cd
$ ls
$ cd libsndfile/
$ sh autogen.sh

// Install autogen, autoconf and automake through brew.

$ make
$ sudo make install

**Comment by PaulBatchelor** [comment]
Thanks for reporting this, Sashank! What you showed me during class was very helpful for me.

OSX installation is a bit sticky only because of libsndfile. 

I haven't been able to successfully get the brew version of libsndfile to work with soundpipe, so the current solution to this problem is to compile libsndfile from source on github. I tell people to do this because I know it will install the libraries in /usr/local/lib and the header files in /usr/local/include. I assumed that OSX would have those locations by default, but they did not in your case, so I ended up having to manually tell GCC to look for the headers and library file by adding -I and -L flags to CFLAGS in the Makefile. The best way to do this would be to put this line at the end of "config.mk":

CFLAGS += -L/usr/local/include -L/usr/local/lib

Or, if the header files and libraries are in nonstandard locations:

CFLAGS += -I path_to_headers -L path_to_library

**Comment by PaulBatchelor** [comment]
It would seem the best approach to installing Soundpipe on OSX is to do the following:

0. Try to build with 'make'
1. install libsndfile via brew: "brew install libsndfile"
2. add the following to bottom of config.mk:
CFLAGS += -L/usr/local/lib -I/usr/local/include 
3. Try to build again with 'make'
