### ISSUE TITLE
Question: which modules can be used for spectral resynthesis

### ISSUE THREAD

**Issue by jamiebullock** [PaulBatchelor/Soundpipe#101]
Hi,

Great work with this library. The README mentions modules for spectral resynthesis, which modules can be used for that. Thanks.

**Comment by PaulBatchelor** [comment]
Hello,

Thank you for the kind words.

Spectral utilities in Soundpipe are pretty limited at the moment, unfortunately. They might work for your needs, they might not. Considering that there are two FFT libraries embedded in Soundpipe, this really shouldn't be the case. Someday I (or someone else) may implement some more spectral modules. But for now...

Spectral resynthesis in SP can be done using [mincer](http://paulbatchelor.github.io/res/soundpipe/docs/mincer.html). The original implementation can be found [as a Csound opcode with the same name](http://www.csounds.com/manual/html/mincer.html). 

This particular implementation is a phase vocoder that reads from in-memory audio data. It can allow, for instance, one to scrub through the file while keeping pitch and time as individual components.

It's quite fun to play around with (it is basically the core algorithm behind the QuBit Nebulae Eurorack module), but it is fairly limited when compared to the other phase vocoders out there. 

Another hyper-specialized module that is *technically* doing spectral resynthesis is an implementation [PaulStretch](http://paulbatchelor.github.io/res/soundpipe/docs/paulstretch.html) algorithm ported in Soundpipe. It is the algorithm responsible for things like [Bieber 800](https://www.youtube.com/watch?v=QspuCt1FM9M). This one works best in offline, but I've managed to get it working in realtime as well. Also reads audio from memory rather than to disk.

**Comment by jamiebullock** [comment]
Thanks @PaulBatchelor for the quick reply. I'm particularly looking for something in C/C++ to do pitched / unhitched separation, but maybe the LPC module could do this?

I'm going to have a general play with Soundpipe though, as it seems super-useful especially with the MIT license.

**Comment by jamiebullock** [comment]
> Not sure we quite have anything like that. Sorry about that. May I ask what you are using it for? Sounds like you are doing stuff related to the vocal processing.

No worries. I'm looking to use if for musical applications, or at least to potentially develop a plugin that could be used for musical applications. So for example, to separate the attack transients and breath noise in a flute sample from the pitched part of the sound.

**Comment by PaulBatchelor** [comment]
Hmmm... It sounds like you may be in need of a dedicated audio analysis library. The source (component?) separation problem you are describing is indeed an interesting one, but it is definitely something that Soundpipe does not have a pre-made solution for (the closest things may be to use tuned bandpass filters). 

I often point folks in the direction of [aubio](https://aubio.org/), which is a GPL library which is more specialized towards analysis and classification of audio. I've used it to do things like realtime beat detection, and it is quite easy to work with. It could be a start. 

There is also [Loris](http://www.cerlsoundgroup.org/Loris/) a C/C++ library that can do things like additive resynthesis and morphing. I haven't used the API, but I have used the command-line tools. GPL'd as well. The sound quality is pretty good. 

I have a distinct feeling that there are some IRCAM Max/MSP objects that possibly do what you describe, but I am not sure.

**Comment by jamiebullock** [comment]
Many thanks for all the info Paul, really appreciate it. I'm aware of those options already. I'm also the author of the [LibXtract](https://github.com/jamiebullock/LibXtract) analysis library, so I'm no stranger to this. I was just looking for something MIT licensed  (or similar) I could use off-the-shelf before reinventing the wheel.

I still think I'll end up using Soundpipe for other stuff as it seems a really useful toolbox that goes a bit beyond what some of the other libs offer. Cheers!
