### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by dreamwieber** [PaulBatchelor/Soundpipe#103]
Hi,

Sorry if I'm missing something obvious here, but I've been reading through the docs and can't find definitions for some of the more terse variable names. 

For instance, osc has iphs and lphs. I deduced iphs is initial phase (and it's documented in C Sound as well.) But, I'm just assuming lphs is the 'current phase' based on looking at how it's used in the code. I don't see it actually commented anywhere. 

Then there's vars like osc->tbl->sicvt. I can't find any comment or docs on that, and lots of other vars. 

Hoping you can point me to docs on these particulars? It's definitely educational to reverse engineer their definitions by reading the source, but it's pretty time consuming. My C is a little rusty, so forgive me if these are obvious conventions. 

Thanks!

**Comment by PaulBatchelor** [comment]
> can't find definitions for some of the more terse variable names.

You can thank Csound for those. They have a lot of those! Documentation on these is minimal, unfortunately. 

The variables you described are the following:

- iphs: initial phase
- lphs: last phase (this is an incremental value, so it is used to create the current phase)
- sicvt: this stands for Sampling Increment ConVert

The soundpipe oscillator code was particularly challenging for me to wrap my head around. So much so that I created a standalone [literate program](https://en.wikipedia.org/wiki/Literate_programming) using CWEB. These variables, as well as the underlying algorithm can be found [on a separate github page](https://github.com/PaulBatchelor/the_oscillator). The code is slightly modified from the soundpipe module `sp_osc` and the data structure `sp_ftbl`, but conceptually it is identical. 

CWEB should come shipped with most TeX/LaTeX systems such as texlive, but in case it doesn't, I have attached the generated PDF. I hope it is useful for you. 

[oscillator.pdf](https://github.com/PaulBatchelor/Soundpipe/files/2069163/oscillator.pdf)

**Comment by dreamwieber** [comment]
Ah, thank you so much for taking the time to respond with such a thorough answer — this should be enough to get me on my way when I come back to the code tonight.

My background is in ObjectiveC so I’ve become used to ridiculouslyDescriptiveVariableNames :)

Thanks again, happy hacking.
