### ISSUE TITLE
No  "soundpipe.h"？

### ISSUE THREAD

**Issue by ucasiggcas** [PaulBatchelor/Soundpipe#110]
Dear,

Thanks to your great project,

but when I use to get the pitch with the [script](https://github.com/PaulBatchelor/Soundpipe/blob/master/examples/ex_ptrack.c)
it tells me no such file,

What happened?

Could U help me ?

Thanks a lot.

**Comment by ucasiggcas** [comment]
And it's not easy to run the ex_ptrack.c

**Comment by fennecdjay** [comment]
You don't.
In the example directory, run 
``` sh
make
```

then,  for ptrack:
```
./ex_ptrack.bin 
```
Tihis generates `test.wav`.

**Comment by ucasiggcas** [comment]
@fennecdjay 
Thx,
but if I want to get a wav file pitch,
Could U tell me what should I do ?
Thanks a lot.

**Comment by fennecdjay** [comment]
You should try editing or (copying, renaming and modifying) ex_ptrack.c.
Replace the saw by a wav reader reading your target (or your command line argument).

**Comment by ucasiggcas** [comment]
Thanks

but it's not easy to run the project without bugs.

**Comment by ucasiggcas** [comment]
Dear,
When I make

![image](https://user-images.githubusercontent.com/35590066/57924038-9171ce80-78d6-11e9-88ed-43c45e0c89f6.png)

**Comment by fennecdjay** [comment]
Did you not build the lib?
```
XXX:~/AudioKit/Soundpipe/# make
```
then you can build the examples.

**Comment by PaulBatchelor** [comment]
I can confirm that @fennecdjay is correct. You need to compile the library first before compiling the examples. Then your problem will be solved. Please update us on your progress.

No need to read onwards, unless you want to learn about some Soundpipe internals.

The reason why `soundpipe.h` is missing is because it is a file that gets generated when you build the the library. This  header file is a combination of all the separate module header files in the `h` directory. As of writing, the current process of header file generation can be found [here](https://github.com/PaulBatchelor/Soundpipe/blob/35d856fcf8a0d85c285818554f569b592d066d10/Makefile#L51-L58) as a Makefile recipe.

Having a single header file makes it very easy to drop into places, but a single header file is not ideal for this kind of library, which is really a decentralized collection of things. I wanted to make each soundpipe module easily extractable, so I made sure each module file had their own header file (located in `h/`) to go with their C file (located in `modules`). That's my reasoning for the current design.

**Comment by ucasiggcas** [comment]
Thanks ,

but I don't think so

![image](https://user-images.githubusercontent.com/35590066/58005006-3844ad80-7b17-11e9-844b-d92a53e9cd13.png)

**Comment by PaulBatchelor** [comment]
This is a more unusual problem. Out of curiosity, what OS are you using? I think I remember running into issues like this on Windows. This a problem related to libsndfile, an optional third-party library enabled by default. If you don't think you'll be needing libsndfile, you can build soundpipe without it (AudioKit does it this way, IIRC).

Here is how you'd do it:

```
make clean
make NO_LIBSNDFILE=1
```

Please let me know if things build okay.

**Comment by PaulBatchelor** [comment]
@ucasiggcas any progress?

**Comment by ucasiggcas** [comment]
@PaulBatchelor 
Thanks，

OS:Ubuntu18

I find the sndfile.h from the github somewhere,
but maybe it used not very good.
I think the libsndfile is the key to solve the problem,

You proposed the AudioKit ,I know it's very useful in pitch tracking,
Is there any C++ (only) scripts/projects ?
If I could use the AudioKit in C++ !

**Comment by PaulBatchelor** [comment]
> OS:Ubuntu18

Good to know. Usually, Linux is supposed to be the easiest platform to compile soundpipe on. I am sorry you are running into troubles.

> I find the sndfile.h from the github somewhere

This sounds wrong.

> I think the libsndfile is the key to solve the problem

I think you are right.

libsndfile (and sndfile.h) should be installed via the ubuntu package manager. 

Please remove the `sndfile.h` file you found on github.

Then you can try running something like `sudo apt install libsndfile-dev`.

After that, in the soundpipe directory, run

```
make clean
make
```

> Is there any C++ (only) scripts/projects ?

It is different, but SuperCollider language is a C++ project that has many pitch tracking algorithms. It will be much harder to compile than Soundpipe.

You are so close to getting Soundpipe to work, so why stop now?

**Comment by ucasiggcas** [comment]
@PaulBatchelor 
Thanks 

but when I make,also have some warnings,
![image](https://user-images.githubusercontent.com/35590066/58762660-a449fb80-8584-11e9-9f48-611218249820.png)
![image](https://user-images.githubusercontent.com/35590066/58762667-b035bd80-8584-11e9-8446-df7f73ac17ba.png)
![image](https://user-images.githubusercontent.com/35590066/58762670-b88df880-8584-11e9-999e-638bc70966dc.png)
![image](https://user-images.githubusercontent.com/35590066/58762674-bf1c7000-8584-11e9-811b-731378020cf0.png)
maybe I finally got the success,
![image](https://user-images.githubusercontent.com/35590066/58762712-17537200-8585-11e9-88f8-c931cc9d2210.png)

but could I move the projects in cellphone ?
Just in the PC is not useful

**Comment by PaulBatchelor** [comment]
Yup you got soundpipe to compile now. The warnings are harmless for the most part. I my best to fix them all, but different compilers have different levels of noisiness.

> but could I move the projects in cellphone ?
> Just in the PC is not useful

This is a question beyond the scope of this issue, but I will answer it.

The short answer is yes, but it will take some work. Soundpipe is a very portable library, but it needs to be compiled to the target platform. Right now, you only compiled Soundpipe to work on PC. If you want to get Soundpipe to work on a mobile platform such as iOS or Android, you will have to figure that out yourself, as it is beyond the project scope of Soundpipe.

Some hints: if you are interested in getting Soundpipe to work on iOS, look into CoreAudio. If you are interested in Android, look into NDK, OpenSL, native audio examples and maybe AAudio. Oboe is a recommended C++ framework to use, but I have not used it myself. I would focus on one or the other to begin with.

Since soundpipe.h has now been successfully generated, and you were able to successfully compile the soundpipe library, I consider this issue resolved.
