### ISSUE TITLE
Request: Resonance HP Filter

### ISSUE THREAD

**Issue by romancfischer** [PaulBatchelor/Soundpipe#112]
I know this is a bit off-topic but I was looking for a resonance high pass filter and was  wondering how difficult it would be to invert the moogladder filter for this?

I am currently subtracting the moggladder signal from the original signal like this:
highpass(n) = signal(n) - lowpass(n)

It works but I read somewhere that this would not be the proper way to do this. To be honest, I have some problems understanding the equations explained here:

https://dsp.stackexchange.com/a/20177
https://dsp.stackexchange.com/a/21905

does anyone know a proper and quick way to achieve this?

**Comment by PaulBatchelor** [comment]
An inverted moogladder filter could sound interesting. Trying to do it directly from the C code may prove to be difficult.

The filter implemented here is based on the one described in this paper:

https://pdfs.semanticscholar.org/c490/4c04a7be1d675e360409178da71a1253f6d8.pdf

As far as moog filter emulations go, this one is fairly sophisticated. From the looks of things, this filter is derived directly from the analog circuit as a non-linear physical model, rather than being approximated with a series of biquads (as most models tend to do). My guess is that changing it to be a high pass filter may prove to be a non-trivial task.

If all you are looking for is any old resonant highpass filter, I recommend trying out FAUSTs `resonhp`, found in their standard library.

https://faust.grame.fr/doc/libraries/index.html#fi.resonhp

 You can use FAUST to generate very portable C/C++ code. If one is feeling brave, they can look at the [script used to generate a soundpipe module from FAUST code](https://github.com/PaulBatchelor/Soundpipe/blob/master/util/faust/compile.sh). It's been a while since I've used it. I remember it being kind of janky when I last used it, so who knows what it will be like now.

**Comment by romancfischer** [comment]
excellent answer, thanks! I will take a look at FAUSTs resonhp, the rest is beyond my scope ... :)

**Comment by PaulBatchelor** [comment]
At some point, I *may* build a resonhp port to soundpipe. I'll either look at the underlying FAUST/C source and write it in plain C, or I'll attempt to revive the faust2sp converter. I don't really have much time to work on Soundpipe much, so expect nothing.

**Comment by PaulBatchelor** [comment]
Huh. @romancfischer it seems you may have been on to something initially. Seems like `resonhp` is derived by subtracting the input signal from the lowpass filter. The only difference is that the resonance (called `gain` in the FAUST code) is used as a multiplier by the input signal.

The FAUST code being:

```
resonhp(fc,Q,gain,x) = gain*x-resonlp(fc,Q,gain,x);
```

Source (with comments above):
https://github.com/grame-cncm/faustlibraries/blob/bace8716743372c12a2fabbba1f8484f4d6f8202/filters.lib#L1286-L1306

FAUST DSP algorithms are written by people who know exactly what they are doing. If it works for them, it will work for you. Trying seeing if that gain trick makes a difference in the sound?

**Comment by romancfischer** [comment]
@PaulBatchelor that‘s very interesting! I‘m just wondering if this can be applied to the moogladder as well. In the second post I shared above it says something about applying his equation to a lowpass filter with linear phase response. Does the moogladder satisfy this requirement? I‘ll give this a try anyway.. thanks!

**Comment by romancfischer** [comment]
oh probably this is what you meant with non-linear physical model. I see, then I have to look for another resonant lowpass filter that I can use

**Comment by PaulBatchelor** [comment]
@romancfischer you are welcome to try inverting the moogladder filter with the method used in the FAUST code. It might work out, but I don't have the mathematical intuition to know for sure until I actually try it and hear it for myself.

I may at some point have a weekend to hand-code FAUST's resonhp and resonlp in one go. Soundpipe could use some more filter designs that do bilinear transformations.

**Comment by PaulBatchelor** [comment]
Closing because there isn't any immediate plan to implement resonant HP filter module for soundpipe, but several alternative solutions have been provided.
