### ISSUE TITLE
Better error handling for malloc

### ISSUE THREAD

**Issue by elfring** [PaulBatchelor/Soundpipe#3]
Would you like to add more error handling for return values from functions like [malloc()](https://github.com/PaulBatchelor/Soundpipe/blob/33de9bd2b16e1c08bd50ce7b9be76f0fc2b8c72b/modules/noise.c#L5 "Unchecked memory allocation in sp_noise_create()")?

**Comment by PaulBatchelor** [comment]
Yup. That's a great call. 

In future releases, I plan on giving soundpipe the ability to call non-standard malloc, free, and memset functions. 

In the meantime, it's simple enough to create your own sp_xxx_create module function with error handling of your choosing and use that instead of mine. There is also an aux memory type that could certainly use error handling.
