### ISSUE TITLE
Can't build on OSX (anymore)

### ISSUE THREAD

**Issue by postspectacular** [PaulBatchelor/Soundpipe#56]
Hi Paul,

I've just tried rebuilding the latest master, but it seems the new Makefile is not compatible with OSX anymore (at least not 10.8.5). The problem is with the specified linker options `-shared` and `-fPIC`.

I've tried using `-dylib` instead of `-shared`, which seems to be the OSX linker's equivalent, however it then complains about the "unknown" `-fPIC` option...

Alas I've got no real experience w/ dynamic libs on OSX, so can't offer any guidance...

**Comment by PaulBatchelor** [comment]
I have pushed a change to master so that the makefile no longer builds a dynamic library by default (It's only needed for Chorth).

If you're on dev, in config.mk, you just comment out the the lines following the comment "Build dynamic library" and things should work just fine.

Let me know if things work out okay!

**Comment by postspectacular** [comment]
Yep, that works! Thanks a bunch! :)
